services:
  wordpress02:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secure_pass
      WORDPRESS_DB_NAME: wordpress02
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress02.rule=Host(`wordpress02.vps1.m89.pl`)"
        - "traefik.http.routers.wordpress02.entrypoints=websecure"
        - "traefik.http.routers.wordpress02.tls.certresolver=le"
        - "traefik.http.services.wordpress02.loadbalancer.server.port=80"
        - "traefik.http.routers.wordpress02.service=wordpress02@swarm"
    networks:
      - traefik-net

  db2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_pass
      MYSQL_DATABASE: wordpress02
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secure_pass
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - traefik-net

volumes:
  wordpress_data:
  db_data:

networks:
  traefik-net:
    external: true
