name: Docker Image CI
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy_via_ssh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Kopiowanie plików na serwer i uruchomienie docker-stack
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-stack.yml"
          target: "~/app"

      - name: Deployment aplikacji przez SSH (docker-stack)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/app
            docker stack deploy -c docker-stack.yml wordpress02
